from typing import Protocol

from ..models import LocatorSpec, Observation


class Surface(Protocol):
    def goto(self, url: str) -> None: ...

    def observe(self) -> Observation: ...

    def click(self, locator: LocatorSpec, timeout_ms: int) -> None: ...

    def fill(self, locator: LocatorSpec, value: str, timeout_ms: int) -> None: ...

    def extract(self, locator: LocatorSpec, timeout_ms: int) -> str: ...

    def text_present(self, text: str) -> bool: ...

    def screenshot(self, path: str) -> None: ...
